version: '3.9'
services:
  readme.account.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.account.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: alina
      MONGO_INITDB_ROOT_PASSWORD: 1234567
      MONGO_INITDB_DATABASE: readme-accounts

    ports:
      - 27017:27017

    volumes:
      - readme.mongo.account:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb://alina:1234567@localhost:27017/?authSource=readme-accounts --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  readme.account.mongo.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme.account.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: alina
      ME_CONFIG_BASICAUTH_PASSWORD: 1234567
      ME_CONFIG_MONGODB_ADMINUSERNAME: alina
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234567
      ME_CONFIG_MONGODB_URL: mongodb://alina:1234567@readme.account.mongo:27017/

volumes:
  readme.mongo.account:
