# 1.1. Регистрация новых пользователей.
POST http://localhost:3005/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "mik@gmail.com",
  "firstname": "mik",
  "lastname": "Ross",
  "password": "1234567",
  "avatarUrl": "https://15.design.htmlacademy.pro/static/avatar/5.jpg"
}

###

# Регистрация по паролю и емайлу
POST http://localhost:3005/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "alina@gmail.com",
  "password": "1234567"
}

###

# Получение новой пары JWT
POST http://localhost:3005/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsImxhc3RuYW1lIjoiU21pdGgiLCJmaXJzdG5hbWUiOiJLZWtzIiwidG9rZW5JZCI6IjBiMzk0NDA1LWM0ZTQtNGRmMy04NGNjLTg4ZTI5YTRiOGJkZiIsImlhdCI6MTcxNDY2NDEwOSwiZXhwIjoxNzE3MjU2MTA5fQ.A_-yL6zgW1H6VJbfMzXpQvJnK5flYjpwYOZiCxybnio

###

# 1.19. Смена пароля пользователя.
PATCH http://localhost:3005/api/users/change-password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDI4NThlMjQ0YTI5MTc0ODEzNmExNCIsImVtYWlsIjoidGVzdC11c2VyNTdAbWFpbC5ydSIsIm5hbWUiOiJUZXN0VXNlciIsImlhdCI6MTcxNTYzNjQ3MCwiZXhwIjoxNzE1NzIyODcwfQ.aQaOlTCIDoEUybFnVCtVbTO3J5Xw4JnWzFv_gyTCis4
Content-Type: application/json

{
  "oldPassword": "1234567",
  "newPassword": "7654321"
}

###

# Получение публичной информации о пользователе (количество постов - только статус «Published»!)
GET http://localhost:3005/api/users/6642858e244a291748136a14 HTTP/1.1

###
