# Get user by ID
GET http://localhost:4000/api/auth/test HTTP/1.1

###

# Create a new user
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "gim@gmail.com",
  "firstname": "gim",
  "lastname": "Ross",
  "password": "1234567",
  "avatarUrl": "https://15.design.htmlacademy.pro/static/avatar/6.jpg"
}

###

# Get user by ID

GET http://localhost:4000/api/auth/66c0ce8db8eee6c5990c0a85 HTTP/1.1

###

# Login user by email and password
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "alina@gmail.com",
  "password": "1234567"
}

###

# Get new JWT pair
POST http://localhost:4000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmMwY2U4ZGI4ZWVlNmM1OTkwYzBhODUiLCJlbWFpbCI6Im5pa0BnbWFpbC5jb20iLCJsYXN0bmFtZSI6IlJvc3MiLCJmaXJzdG5hbWUiOiJuaWsiLCJ0b2tlbklkIjoiMjQ1NDYwZjUtY2U3Yy00ZTYxLWI3YTYtZjJiYWQ2ODZhYjA5IiwiaWF0IjoxNzIzOTYwMTIxLCJleHAiOjE3MjY1NTIxMjF9.tWHPX1gPMIa4kT03Dl4IsA2G9VLcxvvpOxy6lVuaMlA

###

# Check user token
POST http://localhost:4000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmMwY2U4ZGI4ZWVlNmM1OTkwYzBhODUiLCJlbWFpbCI6Im5pa0BnbWFpbC5jb20iLCJsYXN0bmFtZSI6IlJvc3MiLCJmaXJzdG5hbWUiOiJuaWsiLCJpYXQiOjE3MjM5NTc1MjMsImV4cCI6MTcyNDA0MzkyM30.KO8L0UIrOOXm8xyoRbKfqPx6_81mOzqPiwT6OdEPaHE

###

# Change user password
PATCH http://localhost:4000/api/auth/change-password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBjZThkYjhlZWU2YzU5OTBjMGE4NSIsImVtYWlsIjoibmlrQGdtYWlsLmNvbSIsImxhc3RuYW1lIjoiUm9zcyIsImZpcnN0bmFtZSI6Im5payIsImlhdCI6MTcyMzk2MTEzNywiZXhwIjoxNzI0MDQ3NTM3fQ.aFnCFBLDgpwKJmU9mlVEF3UayJVLVuoMQyG712u98M0
Content-Type: application/json

{
  "oldPassword": "7654321",
  "newPassword": "1234567"
}

###

# Subscribe on an other user
PATCH http://localhost:4000/api/auth/subscribe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBjZThkYjhlZWU2YzU5OTBjMGE4NSIsImVtYWlsIjoibmlrQGdtYWlsLmNvbSIsImxhc3RuYW1lIjoiUm9zcyIsImZpcnN0bmFtZSI6Im5payIsImlhdCI6MTcyMzk2Mzg5MywiZXhwIjoxNzI0MDUwMjkzfQ.PHSQmv875CQauOqBWHTcmrIGjZPSN5k8TtrSGV6v8VI
Content-Type: application/json

{
  "userId": "66c0cfadfa599e28fa94aa6c"
}

###

# Get a list of users to collect data in API Gateway
POST http://localhost:4000/api/auth/get-users-by-id HTTP/1.1
Content-Type: application/json

{
  "usersIds": ["66c0cfadfa599e28fa94aa6c", "66c0cef258e1d23490d04420"]
}

###

# Get a list of publishers the current user is subscribed to
GET http://localhost:4000/api/auth/get-publishers-list HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzBjZWYyNThlMWQyMzQ5MGQwNDQyMCIsImVtYWlsIjoiYWxpbmFAZ21haWwuY29tIiwibGFzdG5hbWUiOiJSb3NzIiwiZmlyc3RuYW1lIjoiYWxpbmEiLCJpYXQiOjE3MjM5NjU5MzIsImV4cCI6MTcyNDA1MjMzMn0.5Qgy7M2EfQTrSNN_5LmxEHAmitXuQA775ENSLeLBnDU
###
