version: '3.9'
services:
  readmy.file-storage.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.file-storage.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme.mongo.file-storage:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/?authSource=${MONGO_DB} --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  readmy.file-storage.mongo.ui:
    image: mongo-express:1.0-20
    restart: always
    container_name: readme.file-storage.mongo.ui
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.file-storage.mongo:27017/

volumes:
  readme.mongo.file-storage:
